In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.0.0+cu117


## Introduction to Tensors -> https://pytorch.org/docs/stable/tensors.html

### Create tensors

In [6]:
# scalar
scalar = torch.tensor(7)
print(scalar.ndim)
print(scalar.item())  # get tensor back as Python int

0
7


In [7]:
# vector
vector = torch.tensor([7, 7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [10, 5]])
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])

2
torch.Size([2, 2])
tensor([7, 8])


In [14]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

![00-pytorch-different-tensor-dimensions.png](static/00-pytorch-different-tensor-dimensions.png)

### Random tensors
#### Start with random numbers -> look at data -> update rn -> look at data -> ...

In [16]:
# Create a random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1356, 0.5702, 0.8434, 0.7994],
        [0.3165, 0.1431, 0.6322, 0.0974],
        [0.1626, 0.5397, 0.5737, 0.6531]])

In [18]:
# Create a rand tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224))  # h,w,c
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Ones, zeros, eye

In [25]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros * torch.rand(size=(3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3, 5), dtype=torch.int)
ones

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [24]:
eye = torch.eye(10)
eye

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Create a range of tensors and tensors-like

In [29]:
# Range
one_to_14 = torch.arange(0, 14, 3)
one_to_14

tensor([ 0,  3,  6,  9, 12])

In [31]:
# Tensors like
zeros = torch.zeros_like(input=one_to_14)
zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes -> https://pytorch.org/docs/stable/generated/torch.Tensor.requires_grad_.html

In [35]:
float_32_tensor = torch.tensor([3.0, 2.5],
                               dtype=None,  # What type tensor has
                               device="cuda",  # alt = "cpu"
                               requires_grad=False)
float_32_tensor

tensor([3.0000, 2.5000], device='cuda:0')

In [37]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.0000, 2.5000], device='cuda:0', dtype=torch.float16)

### Getting info from tensor --- Attributes

In [42]:
print(float_32_tensor.dtype)  # To get type of tensor
print(float_32_tensor.shape)  # To get tensor shape
print(float_32_tensor.size())  # To get tensor size
print(float_32_tensor.device)  # To get tensor device

torch.float32
torch.Size([2])
torch.Size([2])
cuda:0


### Tensor operations

In [44]:
# Setup
tensor_one = torch.tensor([1, 2, 3])
tensor_two = torch.tensor([5, 6, 7])

In [45]:
# Addition
print(tensor_one + 10)
print(tensor_one + tensor_two)

tensor([11, 12, 13])
tensor([ 6,  8, 10])


In [46]:
# Subtraction
print(tensor_one - 10)
print(tensor_one - tensor_two)

tensor([-9, -8, -7])
tensor([-4, -4, -4])


In [48]:
# Multiplication - element-wise
print(tensor_one * 10)
print(torch.mul(tensor_one, 5))
print(tensor_one * tensor_two)

tensor([10, 20, 30])
tensor([ 5, 10, 15])
tensor([ 5, 12, 21])


In [49]:
# Division
print(tensor_one / 10)
print(torch.div(tensor_one, 5))
print(tensor_one / tensor_two)

tensor([0.1000, 0.2000, 0.3000])
tensor([0.2000, 0.4000, 0.6000])
tensor([0.2000, 0.3333, 0.4286])


In [64]:
# Matrix
print(torch.matmul(tensor_one, tensor_two))
print(tensor_one @ tensor_two)

matrix_one = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix_two = torch.tensor([[8, 9], [10, 11], [15, 3]])
print(matrix_one @ matrix_two)

matrix_one = torch.rand(5, 7, 3, 8)
matrix_two = torch.rand(5, 7, 8, 2)
matrix_three = matrix_one @ matrix_two
matrix_three.shape

tensor(38)
tensor(38)
tensor([[ 73,  40],
        [172, 109]])


torch.Size([5, 7, 3, 2])

In [67]:
### Transpose
M = torch.rand(2, 3)
print(M.T.shape)
M @ M.T

torch.Size([3, 2])


tensor([[1.0965, 1.1255],
        [1.1255, 1.4479]])